---
- name: Playbook to configure AAP
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - awx.awx

  pre_tasks:
    - name: Include vars from controller_configs dir
      ansible.builtin.include_vars:
        dir: ./controller_configs
        extensions: [yml]

  roles:
    - { role: infra.aap_configuration.controller_job_templates}
