---
- name: Remove LAMP Stack on RHEL 9
  hosts: all
  tasks:
  
    - name: Stop and Disable Apache
      ansible.builtin.systemd_service:
        name: httpd
        state: stopped
        enabled: false

    - name: Stop and Disable MariaDB
      ansible.builtin.systemd_service:
        name: mariadb
        state: stopped
        enabled: false
        
    - name: Remove Apache
      ansible.builtin.dnf:
        name: httpd
        state: absent

    - name: Remove MariaDB
      ansible.builtin.dnf:
        name: mariadb-server
        state: absent

    - name: Remove PHP and common modules
      ansible.builtin.dnf:
        name:
          - php
          - php-mysqlnd
          - php-fpm
          - php-opcache
          - php-gd
          - php-xml
          - php-mbstring
        state: absent

    - name: Disconnect from Red Hat Subscriptions and Red Hat Network
      community.general.redhat_subscription:
        state: absent
        activationkey: "{{ key }}"
        org_id: "{{ org_id }}"
    
